---
dependency:
  name: galaxy
driver:
  name: delegated
  host: "${LIBVIRT_HOST-localhost}"
  libvirt_uri: "${LIBVIRT_URI-qemu:///system}"
  logfile: "${LIBVIRT_LOGFILE-~/.cache/virt-up/virt-up.log}"
  loglevel: "${LIBVIRT_LOGLEVEL-info}"
  python_interpreter: "${LIBVIRT_PYTHON-/usr/bin/python3}"
platforms:
  - name: m-builder02
    template: generic-centos-7
    memory: 2048
    cpus: 4
    groups:
      - rpm_builders
provisioner:
  name: ansible
  playbooks:
    cleanup: ../../playbooks/cleanup-build.yml
    converge: ../../playbooks/build.yml
    create: ../../playbooks/create-libvirt.yml
    destroy: ../../playbooks/destroy-libvirt.yml
    prepare: ../../playbooks/prepare.yml
    verify: ../../playbooks/verify-build.yml
  inventory:
    host_vars:
      m-builder02:
        sysname: amd64_linux26
        dist: el7
        arch: x86_64
    group_vars:
      rpm_builders:
        ref: "${OPENAFS_REF-master}"
        repo: "${OPENAFS_REPO-https://github.com/openafs/openafs.git}"
        builddir: ~/openafs
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
  create_sequence:
    - create
    - prepare
  converge_sequence:
    - create
    - prepare
    - converge
  check_sequence:
    - verify
  destroy_sequence:
    - cleanup
    - destroy
