---
- name: Autoconf
  command:
    cmd: ./regen.sh
    chdir: "{{ afs_source }}"

- name: Generate makefile
  command:
    cmd: ./configure --disable-kernel-module
    chdir: "{{ afs_source }}"

- name: Create source distribution files
  command:
    cmd: make dist
    chdir: "{{ afs_source }}"

- name: Create archive
  archive:
    path: "~/openafs/packages/"
    dest: "openafs-{{ afs_version }}-sdist.tar.gz"
    format: gz

- name: Download
  fetch:
    flat: yes
    src: "openafs-{{ afs_version }}-sdist.tar.gz"
    dest: "{{ afs_builds }}/"
  register: fetch_results

- name: Downloaded
  debug:
    var: fetch_results.dest
