---
- set_fact:
    afs_source: '~/openafs'
  when: afs_source is undefined

- name: Checkout source
  git:
    repo: "{{ afs_git_repo | d('git@git.openafs.org/openafs.git') }}"
    version: "{{ afs_git_version | d('master') }}"
    dest: "{{ afs_source }}"

- name: Determine version string
  command:
    cmd: build-tools/git-version .
    chdir: "{{ afs_source }}"
  changed_when: false
  register: git_version

- set_fact:
    afs_version: "{{ git_version.stdout | replace('-', '_') }}"
