---
dependency:
  name: galaxy
driver:
  name: delegated
  host: "${LIBVIRT_HOST-localhost}"
  libvirt_uri: "${LIBVIRT_URI-qemu:///system}"
  logfile: "${LIBVIRT_LOGFILE-~/.cache/virt-up/virt-up.log}"
  loglevel: "${LIBVIRT_LOGLEVEL-info}"
  python_interpreter: "${LIBVIRT_PYTHON-/usr/bin/python3}"
platforms:
  - name: m-builder01
    template: generic-centos-7
    memory: 4096
    cpus: 4
    groups:
      - bdist_builders
provisioner:
  name: ansible
  playbooks:
    cleanup: ../../playbooks/cleanup-build.yml
    converge: ../../playbooks/build-transarc.yml
    create: ../../playbooks/create-libvirt.yml
    destroy: ../../playbooks/destroy-libvirt.yml
    prepare: "${MOLECULE_PREPARE_PLAYBOOK:-../../playbooks/prepare.yml}"
    verify: ../../playbooks/verify-build.yml
  inventory:
    host_vars:
      m-builder01:
        jobs: 1
    group_vars:
      bdist_builders:
        m_gitref: "${M_GITREF:-master}"
        m_gitrepo: "${M_GITREPO:-https://github.com/openafs/openafs.git}"
        afs_bdist_dir: "~/.cache/openafs-robotest/binaries/bdist-transarc"
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
  create_sequence:
    - create
    - prepare
  converge_sequence:
    - create
    - prepare
    - converge
  check_sequence:
    - verify
  destroy_sequence:
    - destroy
