---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: m-builder01
    box: generic/centos7
    memory: 2048
    cpus: 4
    groups:
      - tarball_builders
provisioner:
  name: ansible
  playbooks:
    cleanup: ../../playbooks/cleanup-build.yml
    converge: ../../playbooks/build.yml
    prepare: ../../playbooks/prepare.yml
    verify: ../../playbooks/verify-build.yml
  inventory:
    host_vars:
      m-builder01:
        jobs: 1
    group_vars:
      tarball_builders:
        ref: "${OPENAFS_REF-master}"
        repo: "${OPENAFS_REPO-https://github.com/openafs/openafs.git}"
        builddir: ~/openafs
        configure_options: >
          --enable-transarc-paths
          --enable-checking
          --enable-kernel-module
          --enable-debug
          --enable-debug-kernel
          --enable-supergroups
          --enable-namei-fileserver
          --enable-pthreaded-ubik
verifier:
  name: ansible
scenario:
  test_sequence:
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
  create_sequence:
    - create
    - prepare
  converge_sequence:
    - create
    - prepare
    - converge
  check_sequence:
    - verify
  destroy_sequence:
    - cleanup
    - destroy
