---
- name: Make source distribution
  hosts: all
  tasks:
    - import_role:
        name: openafs_contrib.openafs.openafs_devel

    - name: Checkout source
      git:
        repo: "{{ afs_git_repo }}"
        version: "{{ afs_git_version }}"
        dest: "~/openafs"

    - name: Get version string
      command:
        cmd: build-tools/git-version .
        chdir: "~/openafs"
      changed_when: false
      register: git_version

    - set_fact:
        version: "{{ git_version.stdout | replace('-', '_') }}"

    - name: Autoconf
      command:
        cmd: ./regen.sh
        chdir: "~/openafs"

    - name: Generate makefile
      command:
        cmd: ./configure --disable-kernel-module
        chdir: "~/openafs"

    - name: Create source distribution files
      command:
        cmd: make dist
        chdir: "~/openafs"

    - name: Create archive
      archive:
        path: "~/openafs/packages/"
        dest: "openafs-{{ version }}-sdist.tar.gz"
        format: gz

    - name: Download
      fetch:
        flat: yes
        src: "openafs-{{ version }}-sdist.tar.gz"
        dest: "{{ afs_builds }}/"
      register: fetch_results

    - name: Downloaded
      debug:
        var: fetch_results.dest
