---

- name: Build Transarc-style binary distribution
  hosts: all
  roles:
    - openafs_devel
  tasks:
    - name: Checkout
      git:
        repo: "{{ m_gitrepo }}"
        version: "{{ m_gitref }}"
        dest: "{{ m_builddir | d('~/openafs') }}"
      register: checkout_results

    - name: Build
      openafs_build:
        target: dest
        clean: "{{ checkout_results.changed }}"
        projectdir: "{{ m_builddir | d('~/openafs') }}"
        configure_options:
          enable:
            - transarc_paths
            - debug
            - debug-kernel
            - kernel-module
          with:
            - linux-kernel-packaging
      register: build_results

    - debug:
        var: build_results

    - set_fact:
        tarball: "openafs-{{ build_results.version }}-{{ build_results.sysname }}.tar.gz"
        dist: "{{ ansible_distribution | replace(' ', '_') | lower }}{{ansible_distribution_major_version }}"
        arch: "{{ ansible_architecture }}"

    - name: Create tarball
      archive:
        path: "{{ m_builddir | d('~/openafs') }}/{{ build_results.sysname }}"
        dest: "/tmp/{{ tarball }}"
        format: gz

    - name: Download tarball
      fetch:
        flat: yes
        src: "/tmp/{{ tarball }}"
        dest: "{{ afs_bdist_dir }}/{{ dist }}/{{ arch }}/{{ tarball }}"
      register: fetch_results

    - name: Downloaded
      debug:
        var: fetch_results.dest
