---
- name: Wait for instances
  hosts: all
  gather_facts: no
  tasks:
    - name: Waiting for system to start
      wait_for_connection:

- name: Update
  hosts: all
  tasks:
    # Update the kernel to a recent release in order to install a supported
    # kernel devel package. (Alternatively, a vault repo could be used to
    # install older devel packages if needed?)
    - name: Update Red Hat kernel
      when:
        - m_update_kernel | d('yes') | bool
        - ansible_os_family == 'RedHat'
      become: yes
      block:
        - name: Update kernel
          yum:
            state: latest
            name: kernel
          register: yum_update_kernel
        - name: Reboot
          reboot:
            reboot_timeout: 600
          when: yum_update_kernel.changed

- name: Prepare
  hosts: all
  tasks:
    - name: Set hostname address mapping
      become: yes
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
        backup: yes

    - name: Setup selinux
      become: yes
      selinux:
        policy: targeted
        state: "{{ m_enable_selinux | d('no') | bool | ternary('enforcing', 'permissive') }}"
      when:
        - ansible_selinux.status is defined
        - ansible_selinux.status == 'enabled'
